FROM quay.io/biocontainers/mtbseq:latest
LABEL maintainer="Larry Cai <larrycai.jpl@gmail.com>"

#Install VCFtools
RUN git clone https://github.com/vcftools/vcftools.git && \
	cd vcftools && \
	./autogen.sh && \
	./configure && \
	make && \
	make install && \
	cd /
  
#Install beast 2.x
RUN curl -s "https://api.github.com/repos/CompEvol/beast2/releases" | grep download | grep tgz | head -n 1 | awk '{print $2}' | xargs curl -L -o /beast2.tgz
RUN tar -zxvf beast2.tgz && rm beast2.tgz && mv beast beast2
ENV PATH $PATH:/beast2/bin
